AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-slack-review-rag

  Sample SAM Template for sam-slack-review-rag

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 180

Resources:
  # ------------------------------------------------------------#
  # Lambda
  # ------------------------------------------------------------#

  # Lambda関数
  ReviewReadableCodeFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: "review-readable-code-function"
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Layers:
        - !Ref LayerModules

  # モジュールレイヤー
  LayerModules:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: src/layer_modules/
      CompatibleRuntimes:
        - python3.10
    Metadata:
      BuildMethod: python3.10
